//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RichardSzalay.HostsFileExtension.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RichardSzalay.HostsFileExtension.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new hostname.
        /// </summary>
        internal static string AddHostEntryDescription {
            get {
                return ResourceManager.GetString("AddHostEntryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Hosts Entry.
        /// </summary>
        internal static string AddHostEntryDialogTitle {
            get {
                return ResourceManager.GetString("AddHostEntryDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add....
        /// </summary>
        internal static string AddHostEntryTask {
            get {
                return ResourceManager.GetString("AddHostEntryTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will create host entries for all bindings on this site that are not already configured. Proceed?.
        /// </summary>
        internal static string AddMissingConfirmation {
            get {
                return ResourceManager.GetString("AddMissingConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add All Missing Hosts.
        /// </summary>
        internal static string AddMissingConfirmationTitle {
            get {
                return ResourceManager.GetString("AddMissingConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add any host entries that are not currently configured for this site.
        /// </summary>
        internal static string AddMissingHostEntriesDescriptin {
            get {
                return ResourceManager.GetString("AddMissingHostEntriesDescriptin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add All.
        /// </summary>
        internal static string AddMissingHostEntriesTask {
            get {
                return ResourceManager.GetString("AddMissingHostEntriesTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string AllSearchField {
            get {
                return ResourceManager.GetString("AllSearchField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to delete the selected host entries?.
        /// </summary>
        internal static string DeleteEntriesConfirmation {
            get {
                return ResourceManager.GetString("DeleteEntriesConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Host Entries.
        /// </summary>
        internal static string DeleteEntriesConfirmationTitle {
            get {
                return ResourceManager.GetString("DeleteEntriesConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the selected hostname.
        /// </summary>
        internal static string DeleteHostEntryDescription {
            get {
                return ResourceManager.GetString("DeleteHostEntryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteHostEntryTask {
            get {
                return ResourceManager.GetString("DeleteHostEntryTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to disable the selected host entries?.
        /// </summary>
        internal static string DisableEntriesConfirmation {
            get {
                return ResourceManager.GetString("DisableEntriesConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Host Entries.
        /// </summary>
        internal static string DisableEntriesConfirmationTitle {
            get {
                return ResourceManager.GetString("DisableEntriesConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable selected hostnames.
        /// </summary>
        internal static string DisableHostEntriesDescription {
            get {
                return ResourceManager.GetString("DisableHostEntriesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        internal static string DisableHostEntriesTask {
            get {
                return ResourceManager.GetString("DisableHostEntriesTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the selected hostname.
        /// </summary>
        internal static string EditHostEntryDescription {
            get {
                return ResourceManager.GetString("EditHostEntryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Hosts Entry.
        /// </summary>
        internal static string EditHostEntryDialogTitle {
            get {
                return ResourceManager.GetString("EditHostEntryDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit....
        /// </summary>
        internal static string EditHostEntryTask {
            get {
                return ResourceManager.GetString("EditHostEntryTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to enable the selected host entries?.
        /// </summary>
        internal static string EnableEntriesConfirmation {
            get {
                return ResourceManager.GetString("EnableEntriesConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Host Entries.
        /// </summary>
        internal static string EnableEntriesConfirmationTitle {
            get {
                return ResourceManager.GetString("EnableEntriesConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable selected hostnames.
        /// </summary>
        internal static string EnableHostEntriesDescription {
            get {
                return ResourceManager.GetString("EnableHostEntriesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string EnableHostEntriesTask {
            get {
                return ResourceManager.GetString("EnableHostEntriesTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Address.
        /// </summary>
        internal static string HostEntryForm_AddressLabel {
            get {
                return ResourceManager.GetString("HostEntryForm_AddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Comment.
        /// </summary>
        internal static string HostEntryForm_CommentLabel {
            get {
                return ResourceManager.GetString("HostEntryForm_CommentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Enabled.
        /// </summary>
        internal static string HostEntryForm_EnabledLabel {
            get {
                return ResourceManager.GetString("HostEntryForm_EnabledLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Hostname.
        /// </summary>
        internal static string HostEntryForm_HostnameLabel {
            get {
                return ResourceManager.GetString("HostEntryForm_HostnameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this feature to manage host names in your local hosts file.
        /// </summary>
        internal static string ManageHostsIconDescription {
            get {
                return ResourceManager.GetString("ManageHostsIconDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Local Hosts.
        /// </summary>
        internal static string ManageHostsIconTitle {
            get {
                return ResourceManager.GetString("ManageHostsIconTitle", resourceCulture);
            }
        }
    }
}
