//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RichardSzalay.HostsFileExtension.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RichardSzalay.HostsFileExtension.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action failed.
        /// </summary>
        internal static string ActionFailedTitle {
            get {
                return ResourceManager.GetString("ActionFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new host entry.
        /// </summary>
        internal static string AddHostEntryDescription {
            get {
                return ResourceManager.GetString("AddHostEntryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Hosts Entry.
        /// </summary>
        internal static string AddHostEntryDialogTitle {
            get {
                return ResourceManager.GetString("AddHostEntryDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add....
        /// </summary>
        internal static string AddHostEntryTask {
            get {
                return ResourceManager.GetString("AddHostEntryTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string AllSearchField {
            get {
                return ResourceManager.GetString("AllSearchField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are multiple enabled host entries with the same hostname, which should be avoided. Duplicate entries can be either disabled or deleted..
        /// </summary>
        internal static string ConflictedEntriesDescription {
            get {
                return ResourceManager.GetString("ConflictedEntriesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address for this entry conflicts with the bindings for this site..
        /// </summary>
        internal static string ConflictedEntryTooltip {
            get {
                return ResourceManager.GetString("ConflictedEntryTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to delete the selected host entries?.
        /// </summary>
        internal static string DeleteEntriesConfirmation {
            get {
                return ResourceManager.GetString("DeleteEntriesConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Host Entries.
        /// </summary>
        internal static string DeleteEntriesConfirmationTitle {
            get {
                return ResourceManager.GetString("DeleteEntriesConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the selected host entry.
        /// </summary>
        internal static string DeleteHostEntryDescription {
            get {
                return ResourceManager.GetString("DeleteHostEntryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteHostEntryTask {
            get {
                return ResourceManager.GetString("DeleteHostEntryTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables all active host entries for any binding of this site.
        /// </summary>
        internal static string DisableBindingEntriesDescription {
            get {
                return ResourceManager.GetString("DisableBindingEntriesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable all binding entries.
        /// </summary>
        internal static string DisableBindingEntriesTask {
            get {
                return ResourceManager.GetString("DisableBindingEntriesTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to disable the selected host entries?.
        /// </summary>
        internal static string DisableEntriesConfirmation {
            get {
                return ResourceManager.GetString("DisableEntriesConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Host Entries.
        /// </summary>
        internal static string DisableEntriesConfirmationTitle {
            get {
                return ResourceManager.GetString("DisableEntriesConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable selected host entries.
        /// </summary>
        internal static string DisableHostEntriesDescription {
            get {
                return ResourceManager.GetString("DisableHostEntriesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        internal static string DisableHostEntriesTask {
            get {
                return ResourceManager.GetString("DisableHostEntriesTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This entry is not defined in the local hosts file, but its DNS entry conflicts with the bindings for this site..
        /// </summary>
        internal static string DNSConflictedEntryTooltip {
            get {
                return ResourceManager.GetString("DNSConflictedEntryTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the selected host entries.
        /// </summary>
        internal static string EditHostEntryDescription {
            get {
                return ResourceManager.GetString("EditHostEntryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Hosts Entry.
        /// </summary>
        internal static string EditHostEntryDialogTitle {
            get {
                return ResourceManager.GetString("EditHostEntryDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit....
        /// </summary>
        internal static string EditHostEntryTask {
            get {
                return ResourceManager.GetString("EditHostEntryTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Hosts.
        /// </summary>
        internal static string EditHostsTask {
            get {
                return ResourceManager.GetString("EditHostsTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to enable the selected host entries?.
        /// </summary>
        internal static string EnableEntriesConfirmation {
            get {
                return ResourceManager.GetString("EnableEntriesConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Host Entries.
        /// </summary>
        internal static string EnableEntriesConfirmationTitle {
            get {
                return ResourceManager.GetString("EnableEntriesConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable selected host entries.
        /// </summary>
        internal static string EnableHostEntriesDescription {
            get {
                return ResourceManager.GetString("EnableHostEntriesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string EnableHostEntriesTask {
            get {
                return ResourceManager.GetString("EnableHostEntriesTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;multiple&gt;.
        /// </summary>
        internal static string FieldHasMultipleValues {
            get {
                return ResourceManager.GetString("FieldHasMultipleValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will create host entries for all bindings on this site that are not already configured. Proceed?.
        /// </summary>
        internal static string FixEntriesConfirmation {
            get {
                return ResourceManager.GetString("FixEntriesConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add All Missing Hosts.
        /// </summary>
        internal static string FixEntriesConfirmationTitle {
            get {
                return ResourceManager.GetString("FixEntriesConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some host entries for this site are missing or have a conflicting DNS resolution. Click here to fix them..
        /// </summary>
        internal static string FixEntriesDescription {
            get {
                return ResourceManager.GetString("FixEntriesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix Host Entries.
        /// </summary>
        internal static string FixEntriesTask {
            get {
                return ResourceManager.GetString("FixEntriesTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Address.
        /// </summary>
        internal static string HostEntryForm_AddressLabel {
            get {
                return ResourceManager.GetString("HostEntryForm_AddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Comment.
        /// </summary>
        internal static string HostEntryForm_CommentLabel {
            get {
                return ResourceManager.GetString("HostEntryForm_CommentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Enabled.
        /// </summary>
        internal static string HostEntryForm_EnabledLabel {
            get {
                return ResourceManager.GetString("HostEntryForm_EnabledLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Hostname.
        /// </summary>
        internal static string HostEntryForm_HostnameLabel {
            get {
                return ResourceManager.GetString("HostEntryForm_HostnameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot manage remote hosts as the extension version is not compatible with the version installed locally..
        /// </summary>
        internal static string IncompatibleServiceVersion {
            get {
                return ResourceManager.GetString("IncompatibleServiceVersion", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ManageHostsFeatureImage {
            get {
                object obj = ResourceManager.GetObject("ManageHostsFeatureImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this feature to manage host names in your local hosts file.
        /// </summary>
        internal static string ManageHostsIconDescription {
            get {
                return ResourceManager.GetString("ManageHostsIconDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Local Hosts.
        /// </summary>
        internal static string ManageHostsIconTitle {
            get {
                return ResourceManager.GetString("ManageHostsIconTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the local hosts file in an elevated notepad instance for manual editing.
        /// </summary>
        internal static string OpenInNotepadDescription {
            get {
                return ResourceManager.GetString("OpenInNotepadDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in notepad.
        /// </summary>
        internal static string OpenInNotepadTask {
            get {
                return ResourceManager.GetString("OpenInNotepadTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch the enabled hostname of the selected host entries to {0}, disabling other entries of the same hostname.
        /// </summary>
        internal static string SwitchAddressDescription {
            get {
                return ResourceManager.GetString("SwitchAddressDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select New Address.
        /// </summary>
        internal static string SwitchAddressDialogTitle {
            get {
                return ResourceManager.GetString("SwitchAddressDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Address.
        /// </summary>
        internal static string SwitchAddressTask {
            get {
                return ResourceManager.GetString("SwitchAddressTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switches the host entries for all bindings of this site to {0}, making as few changes to the hosts file as possible.
        /// </summary>
        internal static string SwitchBindingAddressDescription {
            get {
                return ResourceManager.GetString("SwitchBindingAddressDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch all to....
        /// </summary>
        internal static string SwitchBindingsAddressesToManualTask {
            get {
                return ResourceManager.GetString("SwitchBindingsAddressesToManualTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch all to {0}.
        /// </summary>
        internal static string SwitchBindingsAddressTask {
            get {
                return ResourceManager.GetString("SwitchBindingsAddressTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip: You can edit common properties shared by multiple host entries by selecting them and clicking Edit.
        /// </summary>
        internal static string TipEditMultipleItems {
            get {
                return ResourceManager.GetString("TipEditMultipleItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip: You can enable/disable local host entries for a site&apos;s bindings by selecting from the Local Hosts section from the Site&apos;s homepage.
        /// </summary>
        internal static string TipSiteBindingEntries {
            get {
                return ResourceManager.GetString("TipSiteBindingEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip: You can switch between the enabled IP address for a hostname by disabling the others and selecting from the Switch Address menu.
        /// </summary>
        internal static string TipSwitchAddress {
            get {
                return ResourceManager.GetString("TipSwitchAddress", resourceCulture);
            }
        }
    }
}
